version: '3'
services:

  registry:
    image: eclipsebasyx/aas-registry:1.1.0
    container_name: dashboard-registry
    ports:
      - 4000:4000

  dashboard-aas:
    image: eclipsebasyx/dashboard-aas:1.1.0
    container_name: dashboard-aas
    environment:
      - BaSyxDashboardSubmodel_Min=15
#      - BaSyxDashboardSubmodel_Max=30
    ports:
      - 6400:6400

  aas-wrapper:
    image: eclipsebasyx/aas-wrapper:1.1.0
    container_name: aas-wrapper
    ports:
      - 6500:6500